In [1]:
import warnings, pandas

warnings.filterwarnings('ignore')

In [2]:
df_fund = pandas.read_csv('data/fundamental.csv', decimal=',', thousands='.')

for c in ['DIV_YIELD', 'MRG_EBIT', 'MRG_LIQ', 'ROIC', 'ROE', 'CRESC_REC_5A']:
    df_fund[c] = df_fund[c].str.replace('.','')
    df_fund[c] = df_fund[c].str.replace(',','.')
    df_fund[c] = df_fund[c].str.rstrip('%').astype(float) / 100

df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,EV/EBITDA,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,12.08,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,50.88,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,12.95,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,14.70,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-175.74,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000

#### Agro

In [3]:
df_agro = pandas.read_csv('data/agro.csv')
df_agro['SETOR'] = 'Agro'

df_fund = pandas.merge(df_fund, df_agro, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,NaN
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Comercio & Distribuição

In [4]:
df_com = pandas.read_csv('data/comdist.csv')
df_com['SETOR'] = 'Comércio & Distribuição'

df_fund = pandas.merge(df_fund, df_com, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,NaN
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Construção

In [5]:
df_cons = pandas.read_csv('data/const.csv')
df_cons['SETOR'] = 'Construção'

df_fund = pandas.merge(df_fund, df_cons, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,NaN
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Energia

In [6]:
df_energia = pandas.read_csv('data/energia.csv')
df_energia['SETOR'] = 'Energia'

df_fund = pandas.merge(df_fund, df_energia, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,NaN
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Petróleo

In [7]:
df_petroleo = pandas.read_csv('data/petroleo.csv')
df_petroleo['SETOR'] = 'Petroleo'

df_fund = pandas.merge(df_fund, df_petroleo, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,Petroleo
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Seguros

In [8]:
df_seg = pandas.read_csv('data/seg.csv')
df_seg['SETOR'] = 'Seguros'

df_fund = pandas.merge(df_fund, df_seg, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,Petroleo
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,NaN

#### Serviços

In [9]:
df_serv = pandas.read_csv('data/serv.csv')
df_serv['SETOR'] = 'Serviços'

df_fund = pandas.merge(df_fund, df_serv, left_on='PAPEL', right_on='PAPEL', how='left')

df_fund['SETOR_x'] = df_fund.apply(lambda d : d['SETOR_y'] if pandas.isna(d['SETOR_x']) else d['SETOR_x'], axis=1)
df_fund.drop(labels=['SETOR_y'], axis=1, inplace=True)
df_fund.rename(columns={'SETOR_x': 'SETOR'}, inplace=True)


df_fund.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,198165000.0,4.107890e+09,0.01,2.5632,Petroleo
1,GNDI3,66.95,-3584.82,5.84,3.423,0.0281,2.378,79.65,87.05,-6.21,...,0.0393,-0.0009,1.17,0.0309,-0.0016,280278000.0,7.116080e+09,0.53,0.2523,NaN
2,AALR3,17.90,-376.44,1.80,1.863,0.0000,833.000,-21.12,22.50,-2.51,...,0.0828,0.0017,0.83,0.0402,-0.0048,9832420.0,1.175290e+09,0.66,-0.0042,NaN
3,DASA3,22.03,-340.88,1.66,1.238,0.0134,672.000,15.11,78.34,-2.35,...,0.0158,-0.0026,1.17,0.0104,-0.0049,16301300.0,7.418660e+09,0.72,0.3037,NaN
4,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,114453000.0,7.138490e+08,0.00,0.0000,Serviços

In [10]:
df_fund['SETOR'].value_counts()

Energia                    67
Construção                 24
Petroleo                   15
Serviços                   14
Seguros                    14
Comércio & Distribuição    12
Agro                        6
Name: SETOR, dtype: int64

In [11]:
df_fund.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476 entries, 0 to 475
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PAPEL            476 non-null    object
 1   COTACAO          476 non-null    float64
 2   P/L              476 non-null    float64
 3   P/VP             476 non-null    float64
 4   PSR              476 non-null    float64
 5   DIV_YIELD        476 non-null    float64
 6   P/ATIVO          476 non-null    float64
 7   P/CAP_GIRO       476 non-null    float64
 8   P/EBIT           476 non-null    float64
 9   P/ATIV_CIRC_LIQ  476 non-null    float64
 10  EV/EBIT          476 non-null    float64
 11  EV/EBITDA        476 non-null    float64
 12  MRG_EBIT         476 non-null    float64
 13  MRG_LIQ          476 non-null    float64
 14  LIQ_CORR         476 non-null    float64
 15  ROIC             476 non-null    float64
 16  ROE              476 non-null    float64
 17  LIQ_2MESES       476 non-null    float64
 18  PATRIM_LIQ       476 non-null    float64
 19  DIV_BRUT/PATRIM  476 non-null    float64
 20  CRESC_REC_5A     476 non-null    float64
 21  SETOR            152 non-null    object
dtypes: float64(20), object(2)
memory usage: 85.5+ KB

In [13]:
df_fund[~df_fund['SETOR'].isna()].to_csv('data/fundamental_trusted.csv', index=False)